sonar.projectKey=marcelorodrigo_voyageclock
sonar.organization=marcelorodrigo

# Analyze application code and identify the test suite separately.
sonar.sources=app
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts
sonar.sourceEncoding=UTF-8
